server:
  port: 8170 # 服务端口
spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-trade # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
    sentinel:
      transport:
        port: 8081
        dashboard: localhost:8080
  #spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: #123456 #默认为空
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0
  datasource: # mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://216.127.184.152:3306/db_yunzoukj_trade?serverTimezone=GMT%2B8
    url: jdbc:mysql://localhost:3306/db_yunzoukj_trade?serverTimezone=GMT%2B8
    username: root
    password: Zwq2573424062@qq.com
  #spring:
  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mybatis日志
  mapper-locations: classpath:com/yunzoukj/yunzou/service/trade/mapper/xml/*.xml
ribbon:
  ConnectTimeout: 10000 #连接建立的超时时长，默认1秒
  ReadTimeout: 10000 #处理请求的超时时间，默认为1秒
feign:
  sentinel:
    enabled: true

# 贴一个隔壁找的支付key，现在是2021.5.7可用
weixin:
  pay:
    #关联的公众号appid
    appId: wx74862e0dfcf69954
    #商户号
    partner: 1558950191
    #商户key
    partnerKey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    #回调地址
    #notifyUrl: 填自己的
    notifyUrl: http://yunzouedu.free.idcfengye.com/api/trade/weixin-pay/callback/notify